[theme]
base="dark"
primaryColor="#00C851"
backgroundColor="#000000"
secondaryBackgroundColor="#222222"
textColor="#FFFFFF"
font="sans serif"

# Optional: tweak additional settings
# e.g., "textColor" or "font", etc.
